### ISSUE TITLE
Splitting Address bar from tab bar

### ISSUE THREAD

**Issue by cspurrier** [tumpio/bottomui#1]
It would be nice if it was possible to leave the address bar at the top, but put the tab bar on the bottom. Thanks.

**Comment by ivoshm** [comment]
+1
I'm not a big fan of this +1 but your communication is sleeping and I want to refresh it :-). Thanks.

**Comment by tumpio** [comment]
Sorry, I'll awake my communication :)

I'm working with a new addon that supports dragging and dropping toolbars in customize mode. It is then possible to have any combination of toolbar positions. It will be ready soon. I have to finish options, localization support and some other minor things for it. Expect it soon :)

**Comment by ivoshm** [comment]
Thanks for so quick answer, I'm looking forward for your new solution.

**Comment by tumpio** [comment]
It is finished! :)
https://addons.mozilla.org/addon/toolbar-position-changer/

Awaiting for a full review, but you can try it already from that link. Report issues, feature requests here:
https://github.com/tumpio/toolbarpositionchanger/issues
