### ISSUE TITLE
Use this add-on with Firefox mobile 

### ISSUE THREAD

**Issue by pikachat** [tumpio/bottomui#4]
Hello, 

Sorry if this request is completely foolish, but I tried using your add-on on my Android phone and it was impossible ("not compatible with Firefox 34" says the phone). Is there a way to do so? My phone is too big to reach the address bar at the top (Sony z2) :p

**Comment by tumpio** [comment]
Closing because it is not possible to customize the mobile Firefox UI the same way as on desktop.
