### ISSUE TITLE
[request] option to move pdfjs toolbar to bottom too

### ISSUE THREAD

**Issue by PedroHLC** [tumpio/bottomui#5]
When visualizing pdf files in firefox with entire UI on bottom, it gets weird having only the pdfjs toolbar on top. As pdfjs comes enabled by standard in firefox, I would like to request that this add-on also moved pdfjs toolbar to bottom.

Thanks for this wonderful add-on.

**Comment by PedroHLC** [comment]
Sorry didn't see the addon was deprecated.

**Comment by tumpio** [comment]
Hi Pedro, I moved your request to my new addon. Let's see if I can add the option for it.
