### ISSUE TITLE
firefox 47.0 w10x64

### ISSUE THREAD

**Issue by ledemon** [tumpio/bottomui#6]

**Comment by jumois** [comment]
Did you solve it?

**Comment by tumpio** [comment]
Did you solve it?

**Comment by ledemon** [comment]
Hi.
Not, not really, I try using the other addon "toolbar position changer", but if don't use at least two rows (navigation, tabs) or (menu, tabs) or other two at the top, in fullscreen the links below de top dont work.
I use at the top only the menu, and at the bottom the navigation and tabs, no more.

**Comment by tumpio** [comment]
Are you using other add-ons? And do you have title bar disabled?

I'll see if I can find a solution for it.

**Comment by ledemon** [comment]
Hi, with the "toolbar position changer" can't put the tabs bottom the screen, so I now use other addon "tabs on bottom" that move the tabs below the navigation bar (but keeping the tabs at the top of the screen altough the navigation bar are in the bottom of the screen) but make the tabs capable of move with your addon to the bottom. Now, one time used the "tabs on bottom" to make capable to move the tabs, move the tabs to the bottom (until here the links at the top works altough the tab bar is the only one), but with the "tabs on bottom" and the "the addon bar (restored)" (status bar), the tabs can't be put upper the status bar and is a bit ugly, so disable "the addon bar (restored)" and the links at the top of the screen with in maximized can't be selected.

I try disabling all others addons: ublock origin, stilysh, greasemonkey, devedition theme enabler, flashgot, fasterfox, mouse gesture suite, private tab, x-notifier, ubiquity.
I have title bar disable. Ok, enabling the title bar the links work fine.

pd: Sorry for my bad english.
